#!/usr/bin/env python3
"""Canonical homepage design-archetype library (v1, ~44 styles).
Built from an Awwwards + One Page Love + design-taxonomy scrub. Each entry is a
generation-ready art-direction fragment. This is the reusable Bob 'design' library."""

ARCHETYPES = [
 ("01-swiss-international","Swiss International style: strict modular grid, flush-left Helvetica/Akzidenz-Grotesk, generous whitespace, black and white plus one signal red, no decoration, rational and crisp."),
 ("02-editorial-minimal","Editorial minimal: large refined serif or grotesk headlines, wide margins, muted palette, sparse cropped photography, premium restraint."),
 ("03-warm-editorial","Warm editorial: cream and ecru ground, warm serif headlines, muted terracotta and sage accents, subtle film-grain photography, cozy and human."),
 ("04-pastel-soft-minimal","Pastel soft minimal: off-white with soft pastel accents, rounded corners, gentle soft shadows, airy spacing, friendly clean sans."),
 ("05-scandinavian-japandi","Scandinavian Japandi: neutral earthy palette, natural wood and linen textures, balanced negative space, calm sans, serene and warm."),
 ("06-spa-wellness","Spa wellness minimal: sage, sand and blush neutrals, soft serifs, nature macro photography, generous air, restorative calm."),
 ("07-duotone","Bold duotone: a single two-color system, tonal duotone photography, high graphic unity, striking and unified."),
 ("08-brutalism","Web brutalism: raw exposed grid, harsh borders, oversized system Helvetica, monochrome plus one clashing accent, intentionally unpolished, confrontational."),
 ("09-neo-brutalism","Neo-brutalism: thick black borders, hard offset drop-shadows, saturated flat color blocks, chunky grotesk type and buttons, playful and punchy."),
 ("10-grunge-textured","Grunge textured: distressed ink and xerox textures, torn edges, halftone grain, gritty high-contrast, hand-made rebellious energy."),
 ("11-collage-scrapbook","Collage scrapbook: layered photo cutouts, tape and torn paper, ransom-note mixed fonts, halftone, handmade archive feel."),
 ("12-glassmorphism","Glassmorphism: frosted translucent panels with thin light borders over a vivid blurred backdrop, soft glow, layered depth, iOS-modern."),
 ("13-claymorphism","Claymorphism: puffy inflated rounded 3D shapes, soft inner and outer shadows, candy pastel gradients, playful toy-like clay icons."),
 ("14-neumorphism","Neumorphism soft-UI: monochrome surfaces extruded from the background with twin soft light and dark shadows, near-invisible edges, subtle emboss."),
 ("15-aurora-mesh","Aurora gradient-mesh: dreamy animated northern-lights color field, blurred orbs, soft luminous blends on a dark canvas, clean white sans."),
 ("16-data-dense","Data-dense dashboard: tight cards and tables, small mono numerals, elegant charts and sparklines, muted UI chrome, high-signal control-panel."),
 ("17-terminal-dev","Terminal developer-core: monospace throughout, IDE or green-amber-on-black palette, ASCII, code blocks, blinking cursor, engineer-native."),
 ("18-bento-grid","Bento grid: modular rounded tiles of varied sizes, one idea per box, soft borders, per-tile accent, Apple-keynote clarity."),
 ("19-dark-gradient-saas","Dark gradient SaaS: near-black canvas with a violet-blue gradient glow, radial mesh, product-UI dashboard hero, geometric sans, venture-polished."),
 ("20-cinematic-dark","Cinematic dark: near-black filmic stage, one spotlit hero, big moody media, low-key lighting, restrained accent, immersive."),
 ("21-dark-luxe-gold","Dark luxe: black and charcoal with gold and brass accents, thin high-contrast serif, wide elegant kerning, subtle shimmer, opulent and sparse."),
 ("22-fashion-editorial","High-fashion editorial: oversized display serif, full-bleed fashion photography, wide tracking, monochrome plus one accent, aspirational look-book."),
 ("23-art-deco","Art Deco: symmetric geometry, gold on black, chevrons and sunbursts, tall condensed caps, metallic linework, roaring-20s glamour."),
 ("24-playful-dopamine","Playful dopamine color: bright clashing saturated hues, bold rounded display type, big geometric shapes, confetti accents, joyful and energetic."),
 ("25-playful-illustration","Playful illustration: custom bright flat spot-illustrations and friendly characters guiding the page, rounded type, hand-drawn accents, approachable."),
 ("26-corporate-memphis","Corporate Memphis: flat humanist noodle-limb figures, muted brand color blocks, geometric blobs, no shadows, big-tech friendly."),
 ("27-memphis-80s","1980s Memphis: loud postmodern squiggles, zig-zags, terrazzo and confetti, primary-plus-pastel clashes, bold irregular shapes."),
 ("28-hand-drawn","Hand-drawn sketch: marker and pencil linework, scribble accents, handwriting fonts, wonky shapes, notebook-grid paper, human and imperfect."),
 ("29-y2k-chrome","Y2K chrome: liquid-metal chrome type and blobby glossy 3D, bevels, star sparkles, iridescent gradient blues, turn-of-millennium optimism."),
 ("30-vaporwave","Vaporwave: pink, teal and purple, Roman busts, grid horizons, glitch, Japanese text, ironic retro-net dreamscape."),
 ("31-synthwave","Synthwave retro-futurism: neon grid, palm-tree sunset horizon, chrome type, scanlines, 1980s neon-speed fantasy."),
 ("32-cyberpunk-neon","Cyberpunk neon: neon on black, glitch and scanlines, circuit motifs, katakana, HUD overlays, magenta and cyan, high-tech dystopia."),
 ("33-pixel-8bit","Pixel 8-bit: pixel sprites and bitmap fonts, limited retro palette, dithering, hard aliasing, arcade-game charm."),
 ("34-risograph","Risograph print: two or three flat spot inks, visible grain, slight misregistration, halftone, matte-paper handmade feel."),
 ("35-newspaper","Newspaper broadsheet: dense justified serif columns, hairline rules, masthead, drop caps, black-and-white editorial gravitas."),
 ("36-magazine","Magazine editorial spread: dramatic pull quotes, drop caps, grid breaks, big captions, serif and grotesk interplay, image-and-text drama."),
 ("37-bauhaus","Bauhaus: primary red-yellow-blue with black, geometric circles squares and triangles, geometric sans, asymmetric functional balance."),
 ("38-photography-led","Photography-led lifestyle: full-bleed authentic candid photography as the hero, thin elegant type overlaid, minimal chrome, emotional and immersive."),
 ("39-fineart-painterly","Fine-art painterly: expressive brush-stroke textures and painterly canvas, muted gallery palette, refined serif, artful and tactile."),
 ("40-3d-product","3D product render: a hyperreal studio-lit floating product object as hero, soft reflections and shadows, gradient stage, clean minimal sans."),
 ("41-webgl-immersive","Immersive WebGL 3D: a full-viewport real-time 3D scene, particle fields and depth, floating minimal UI, dark base with luminous accents."),
 ("42-kinetic-type","Kinetic typography: an oversized display headline as the entire hero, variable-weight play, letters mid-motion, minimal else, high contrast."),
 ("43-type-specimen","Type specimen big-type: giant foundry-grade display type filling the viewport, minimal supporting elements, letterforms as architecture."),
 ("44-organic-nature","Organic biomorphic: soft fluid blob shapes, wavy dividers, leaf and water motifs, earthy greens and browns, flowing natural curves."),
]

# ── CINEMATIC & ARTFUL family (the sophisticated / premium / professional register) ──
CINEMATIC = [
 ("C01-cinematic-filmstill","Cinematic film-still: a moody, color-graded film-still photograph as the hero, dramatic natural light, shallow depth of field, subtle letterboxing, A24-film sophistication, elegant thin type overlaid."),
 ("C02-monochrome-art-photo","Monochrome fine-art photography: refined black-and-white or desaturated art photography, gallery-grade composition, elegant restraint, high-craft and timeless."),
 ("C03-kinfolk-slow-luxury","Kinfolk slow-luxury editorial: muted natural-light still life, abundant negative space, refined serif, soft neutral palette, understated calm luxury."),
 ("C04-architectural-modern","Architectural modern: architecture and interior photography, concrete, stone and glass, clean structural lines, sophisticated neutral palette, refined and calm."),
 ("C05-quiet-luxury","Quiet luxury / stealth wealth: understated expensive minimalism, muted taupe and greige, elegant thin type, no ornament, effortless restraint."),
 ("C06-apple-grade-product","Apple-grade product minimal: pristine high-craft minimalism, generous whitespace, precise alignment, soft studio product photography, premium and modern."),
 ("C07-modern-fashion-serif","Modern fashion serif editorial: high-contrast Didone serif, striking fashion photography, wide tracking, monochrome plus one accent, contemporary luxury sophistication."),
 ("C08-cinematic-dark-product","Cinematic dark product: a dramatically hero-lit product or data object glowing on deep black, premium tech-brand cinematic staging, refined sans, expensive."),
 ("C09-atmospheric-gradient","Cinematic atmospheric gradient: sophisticated moody film-grade gradients in deep teal, amber and ember, elegant and filmic (not pastel), refined type."),
 ("C10-museum-gallery","Museum gallery modern: art-gallery aesthetic, bright gallery-white walls, generous margins, refined editorial type, artful curatorial calm."),
 ("C11-monochromatic-luxe","Monochromatic luxe: a single deep sophisticated hue system (oxblood, forest green or ink navy) rendered luxuriously with rich tonal depth, elegant serif."),
 ("C12-cinematic-wellness","Cinematic wellness / longevity brand: sophisticated soft natural light, muted clinical-luxe palette, elegant type, aspirational and premium, health made beautiful."),
 ("C13-refined-kinetic-agency","Refined kinetic agency: sophisticated restrained motion, oversized elegant grotesk, disciplined whitespace, high-end creative-agency polish, elegant not playful."),
 ("C14-painterly-modern","Painterly modern abstract: a modern abstract oil-painterly backdrop as fine art, sophisticated muted gallery palette, refined serif over crisp cards."),
 ("C15-editorial-data-art","Premium editorial data-art: beautiful sophisticated data visualization as editorial art, refined thin type, elegant charts, Pentagram-grade polish."),
 ("C16-concrete-luxe","Concrete luxe (refined brutalism): architectural concrete and stone surfaces with elegant restraint, sophisticated material minimalism, refined mono type."),
]

# ── MODERN & CONTEMPORARY family (digital-native, award-winning web-studio aesthetic — NOT lifestyle/interior stock) ──
MODERN = [
 ("M01-modern-editorial-grotesk","Contemporary editorial modern: large clean neo-grotesk (Söhne / Neue Haas Grotesk feel), refined off-white, one sharp accent, precise generous whitespace — the Linear / Vercel / Stripe-press modern-editorial look, digital-native."),
 ("M02-premium-dark-ui","Premium dark UI: refined near-black canvas with a subtle fine grid, crisp real product interface, restrained elegant gradient accents, precise geometric sans — modern SaaS premium (Linear / Vercel / Resend), tasteful not glowy."),
 ("M03-refined-mono-agency","Refined monochrome studio: black and white, oversized contemporary grotesk, disciplined whitespace, high-end creative-studio polish (Obys / Locomotive), elegant and modern."),
 ("M04-bold-colorfield","Modern bold color-field: one confident sophisticated brand color as a full field, crisp contemporary type, minimal geometric shapes — modern brand site (Stripe / Family agency), clean and confident."),
 ("M05-clean-3d-modern","Clean modern 3D: a contemporary minimalist glossy 3D abstract object, soft studio lighting, premium digital-brand render (Cuberto / Igloo Inc), refined sans — crafted and modern, not luxury stock."),
 ("M06-modern-data-ui","Modern data interface hero: a beautiful contemporary product dashboard as the hero, refined modern charts and cards, sophisticated fintech/analytics premium (Mercury / Ramp / Linear), precise."),
 ("M07-sophisticated-gradient","Sophisticated modern gradient: a refined tasteful contemporary mesh gradient (Stripe / Linear era), subtle and premium, clean modern sans — not pastel, not amber-luxury."),
 ("M08-contemporary-type","Contemporary type-forward: oversized modern variable typography as hero, refined editorial-modern, sophisticated restraint, digital-native, not playful."),
 ("M09-warm-modern-minimal","Warm modern minimal: a contemporary warm palette (bone, clay, soft ochre) with modern grotesk and crisp UI — a modern warm digital brand (Notion / Retool feel), refined, NOT spa or interior stock."),
 ("M10-modern-mono-luxe","Modern monochrome luxe: a sophisticated single deep hue as a modern interface system, premium restrained, contemporary type — digital-luxury, not lifestyle."),
 ("M11-editorial-studio-photo","Contemporary art-directed photography: modern conceptual studio photography, bold and design-forward — a modern fashion/tech brand campaign look, refined type — NOT lifestyle or interior stock."),
 ("M12-modern-swiss-grid","Contemporary Swiss grid: a modern precise grid system, refined sophisticated palette, crisp neo-grotesk, contemporary design-studio rigor — structured and modern."),
 ("M13-modern-depth-glass","Refined modern depth: sophisticated subtle glass and layered depth done tastefully (visionOS / Apple premium), clean modern sans, luminous but restrained."),
 ("M14-refined-brutalist-modern","Refined modern brutalism: bold contemporary grotesk, structural blocks, confident but polished — a modern design-studio brutalism (Basement / Studio Lumio), sophisticated not raw."),
]

# ── ART-DIRECTION STYLES (text-only treatments; cross with a fixed content recipe) ──
STYLES = [
 ("mono","MONOCHROME fine-art — black-and-white, dramatic chiaroscuro lighting, gallery-grade composition, refined and timeless."),
 ("cine","CINEMATIC — warm filmic color grade, moody directional light, atmospheric, film-poster energy."),
 ("bold","BOLD EDITORIAL — stark oversized grotesk typography, asymmetric high-craft composition (Obys-studio confidence)."),
 ("clean","CLEAN LIGHT — bright airy editorial, generous whitespace, crisp and premium."),
 ("warm","WARM EDITORIAL — cream/ecru ground, elegant high-contrast serif, muted terracotta accent, subtle grain."),
 ("darkluxe","DARK LUXE — near-black premium ground, subtle gold/glow, refined and expensive."),
 ("museum","MUSEUM GALLERY — bright gallery walls, refined editorial type, artful curatorial calm."),
 ("scientific","SCIENTIFIC / CLINICAL — precise, elegant molecular and biomarker motifs, science made beautiful."),
 ("apple","APPLE-GRADE — pristine studio product minimal, precise, soft studio light."),
 ("painterly","FINE-ART PAINTERLY — expressive painterly texture, muted gallery palette, refined serif."),
 ("cinematic-dark","CINEMATIC DARK — the subject glowing dramatically on deep black, premium, not neon."),
 ("refined-mono","REFINED MONO-AGENCY — crisp black-and-white, disciplined whitespace, high-end studio polish."),
]
