#!/usr/bin/env bash
# repo-map.sh — generate/update docs/repo-map.md.
#
# Usage (run from project root):
#   bash ~/tools/bob-the-builder/scripts/repo-map.sh
#
# What it does:
#   Generates a compressed map of the repo — folder structure, top-level
#   files per folder — that Claude reads at session start instead of
#   grep'ing the codebase. Cuts context cost as projects grow.
#
# Bob the Builder uses this at the Reconcile step ([N]c) to keep the
# map fresh as phases complete.
#
# Safe to run any time; overwrites docs/repo-map.md.

set -euo pipefail

if [[ ! -d .git ]]; then
  echo "ERROR: must be run from the root of a git repo." >&2
  exit 1
fi

mkdir -p docs

OUTPUT_FILE="docs/repo-map.md"
GENERATED_AT="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

{
  echo "# Repo Map"
  echo ""
  echo "Compressed map of the project. Generated by \`scripts/repo-map.sh\` (or \`~/tools/bob-the-builder/scripts/repo-map.sh\` if Bob is installed there). Updated at every Reconcile ([N]c) step per Bob v2.7."
  echo ""
  echo "**Last generated:** $GENERATED_AT"
  echo ""
  echo "## Folder structure"
  echo ""
  echo '```'
  # Use git ls-files to respect .gitignore; group by directory.
  # Portable across BSD awk (macOS) and gawk — sort externally.
  git ls-files | awk -F'/' '
    NF == 1 { print $1; next }
    {
      dir = $1
      for (i = 2; i < NF; i++) dir = dir "/" $i
      dirs[dir]++
    }
    END {
      for (d in dirs) printf "%s/  (%d files)\n", d, dirs[d]
    }
  ' | sort
  echo '```'
  echo ""
  echo "## Top-level files"
  echo ""
  for f in $(git ls-files | awk -F'/' 'NF == 1' | sort); do
    # Skip lockfiles and binary-ish files
    case "$f" in
      *.lock|*.lockb|*-lock.json|*.sum) continue ;;
    esac
    if [[ -f "$f" ]]; then
      size=$(wc -c < "$f" | tr -d ' ')
      lines=$(wc -l < "$f" | tr -d ' ')
      echo "- \`$f\` — ${lines} lines, ${size} bytes"
    fi
  done
  echo ""
  echo "## Notes"
  echo ""
  echo "- This map is auto-generated. Edit the script to change format; don't hand-edit this file (next run overwrites it)."
  echo "- For full file contents, read the file directly."
  echo "- Per Bob v2.7, this file is regenerated at every Reconcile step."
} > "$OUTPUT_FILE"

echo "✅ Wrote $OUTPUT_FILE"
